---
- name: Create db container and connect to network
  docker_container:
    name: microblog
    image: mysql/mysql-server:5.7
    state: started
    restart: yes
    ports:
      - "3306:3306"
    env:
        MYSQL_DATABASE: "microblog"
        MYSQL_USER: "microblog"
        MYSQL_PASSWORD: pass
        MYSQL_ROOT_PASSWORD: pass