---
- name: Install packages
  apt:
      force_apt_get: yes
      name: "{{ packages }}"

#- name: Container present?
#  docker_container:
#      name: "microblog"
#      state: present
#      image: "orkanen/microblog:latest"
#  register: result

#- debug: msg="{{ result.failed }}"

- name: Start docker container
  docker_container:
      name: "microblog"
      image: "orkanen/microblog:flask-exporter"
      state: started
      restart: yes
      ports: 
        - "8000:5000"
      env:
        SECRET_KEY: pass
        DATABASE_URL: mysql+pymysql://microblog:pass@{{ groups.database[0] }}:3306/microblog
#  when: result.failed


- name: Start Node Exporter container
  community.docker.docker_container:
    name: node
    image: prom/node-exporter:v1.4.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    command:
    - "--path.procfs=/host/proc"
    - "--path.rootfs=/rootfs"
    - "--path.sysfs=/host/sys"
    - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"