version: "3"
services:
    test:
        image: orkanen/microblog:test
        container_name: "microblog-test"
        volumes:
            - "./:/home/microblog/"
    prod:
        image: orkanen/microblog:flask-exporter
        container_name: "microblog-flask"
        ports:
            - "7000:5000"
        restart:
            "always"
