root_password: $6$YffDsgxU0NU3.qN$23PWrAMR.LPXNOdZUuiBCu.x.saMOJGHfF5ylC3v/M/Hz7N1hk6nttlF.sDyPAvfChnN5HGpc7F/Ii/Kl44Vx.

server_user: deploy
server_user_password: $6$LD32ureW2D$HKrUinIG680J3Keo97DcQkG1W1HpWGyi.HxkPCNC6NI/Fr9zK/XoKHczkHRk.jtnF.pIn7WEui6OYMkyB./6P0
server_user_groups:
    - sudo

pub_ssh_key_location:
    - ~/.ssh/azure.pub

# WIP - Not sure if working yet.
grafana_user_password: $6$stgglvTTyw$L/5T6rR2p0pedAhtWfM5L6gcHd1hT08bchpLwgyYE4h/CrzFlMpih/mNTursHbJCWbhUKqCdlrNkfC5l/w0cz0

ansible_python_interpreter: /usr/bin/python3
