# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine

WORKDIR /home/deps

# COPY . .
COPY requirements requirements

RUN python -m venv .venv && \
 .venv/bin/pip3 install -r requirements/test.txt

WORKDIR /home/microblog

RUN apk add --no-cache make=4.3-r0

ENTRYPOINT ["./test.sh"]
