FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./
COPY gunicorn_config.py gunicorn_config.py

RUN python -m venv .venv && \
 .venv/bin/pip3 install -r requirements.txt && \
 chmod +x boot.sh && \
 chown -R microblog:microblog ./

ENV FLASK_APP microblog.py

USER microblog

ENV prometheus_multiproc_dir /tmp

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
