---
# WIP - Seems to be working fine, other parts not so much.
- hosts: monitoring
  remote_user: "{{ server_user }}"
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - docker
    - prometheus
    - grafana
    - dashboards